[ROCm] skip SymmetricMemory related UTs for ROCm (#133241)
This features is not yet supported on ROCm.
Skipping:
distributed/test_symmetric_memory.py::SymmetricMemoryTest::test_low_contention_all_gather_symm_mem_input_False
With the errors:
RuntimeError: CUDASymmetricMemory requires PYTORCH_C10_DRIVER_API_SUPPORTED

Fixes #ISSUE_NUMBER
Approved by: https://github.com/pruthvistony, https://github.com/malfet

ghstack-source-id: 48c2a727493d57f1ffbcde43553eabf5f6443362
Pull Request resolved: https://github.com/pytorch/pytorch/pull/133471